<?php
/**
 * NodeTypeEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  Douyin\Open
 * @author   抖音小开
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 */

namespace Douyin\Open\Model;
use \Douyin\Open\ObjectSerializer;

/**
 * NodeTypeEnum Class Doc Comment
 *
 * @category Class
 * @description 富文本处理中的节点类型 1 - text 2 - image
 * @package  Douyin\Open
 * @author   抖音小开
 */
class NodeTypeEnum
{
    /**
     * Possible values of this enum
     */
    const 1 = 1;
const 2 = 2;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::1,
self::2,        ];
    }
}
