<?php
/**
 * VideoCommentListResponseDataList
 *
 * PHP version 5
 *
 * @category Class
 * @package  Douyin\Open
 * @author   抖音小开
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 */

namespace Douyin\Open\Model;

use \ArrayAccess;
use \Douyin\Open\ObjectSerializer;

/**
 * VideoCommentListResponseDataList Class Doc Comment
 *
 * @category Class
 * @package  Douyin\Open
 * @author   抖音小开
 */
class VideoCommentListResponseDataList implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'VideoCommentListResponseDataList';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'comment_id' => 'string',
'comment_user_id' => 'string',
'content' => 'string',
'create_time' => 'int',
'top' => 'bool',
'digg_count' => 'int',
'reply_comment_total' => 'int'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'comment_id' => null,
'comment_user_id' => null,
'content' => null,
'create_time' => null,
'top' => null,
'digg_count' => 'int32',
'reply_comment_total' => 'int32'    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'comment_id' => 'comment_id',
'comment_user_id' => 'comment_user_id',
'content' => 'content',
'create_time' => 'create_time',
'top' => 'top',
'digg_count' => 'digg_count',
'reply_comment_total' => 'reply_comment_total'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'comment_id' => 'setCommentId',
'comment_user_id' => 'setCommentUserId',
'content' => 'setContent',
'create_time' => 'setCreateTime',
'top' => 'setTop',
'digg_count' => 'setDiggCount',
'reply_comment_total' => 'setReplyCommentTotal'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'comment_id' => 'getCommentId',
'comment_user_id' => 'getCommentUserId',
'content' => 'getContent',
'create_time' => 'getCreateTime',
'top' => 'getTop',
'digg_count' => 'getDiggCount',
'reply_comment_total' => 'getReplyCommentTotal'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['comment_id'] = isset($data['comment_id']) ? $data['comment_id'] : null;
        $this->container['comment_user_id'] = isset($data['comment_user_id']) ? $data['comment_user_id'] : null;
        $this->container['content'] = isset($data['content']) ? $data['content'] : null;
        $this->container['create_time'] = isset($data['create_time']) ? $data['create_time'] : null;
        $this->container['top'] = isset($data['top']) ? $data['top'] : null;
        $this->container['digg_count'] = isset($data['digg_count']) ? $data['digg_count'] : null;
        $this->container['reply_comment_total'] = isset($data['reply_comment_total']) ? $data['reply_comment_total'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['comment_id'] === null) {
            $invalidProperties[] = "'comment_id' can't be null";
        }
        if ($this->container['comment_user_id'] === null) {
            $invalidProperties[] = "'comment_user_id' can't be null";
        }
        if ($this->container['content'] === null) {
            $invalidProperties[] = "'content' can't be null";
        }
        if ($this->container['create_time'] === null) {
            $invalidProperties[] = "'create_time' can't be null";
        }
        if ($this->container['top'] === null) {
            $invalidProperties[] = "'top' can't be null";
        }
        if ($this->container['digg_count'] === null) {
            $invalidProperties[] = "'digg_count' can't be null";
        }
        if ($this->container['reply_comment_total'] === null) {
            $invalidProperties[] = "'reply_comment_total' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets comment_id
     *
     * @return string
     */
    public function getCommentId()
    {
        return $this->container['comment_id'];
    }

    /**
     * Sets comment_id
     *
     * @param string $comment_id comment_id
     *
     * @return $this
     */
    public function setCommentId($comment_id)
    {
        $this->container['comment_id'] = $comment_id;

        return $this;
    }

    /**
     * Gets comment_user_id
     *
     * @return string
     */
    public function getCommentUserId()
    {
        return $this->container['comment_user_id'];
    }

    /**
     * Sets comment_user_id
     *
     * @param string $comment_user_id comment_user_id
     *
     * @return $this
     */
    public function setCommentUserId($comment_user_id)
    {
        $this->container['comment_user_id'] = $comment_user_id;

        return $this;
    }

    /**
     * Gets content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string $content content
     *
     * @return $this
     */
    public function setContent($content)
    {
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets create_time
     *
     * @return int
     */
    public function getCreateTime()
    {
        return $this->container['create_time'];
    }

    /**
     * Sets create_time
     *
     * @param int $create_time 时间戳
     *
     * @return $this
     */
    public function setCreateTime($create_time)
    {
        $this->container['create_time'] = $create_time;

        return $this;
    }

    /**
     * Gets top
     *
     * @return bool
     */
    public function getTop()
    {
        return $this->container['top'];
    }

    /**
     * Sets top
     *
     * @param bool $top 是否置顶评论
     *
     * @return $this
     */
    public function setTop($top)
    {
        $this->container['top'] = $top;

        return $this;
    }

    /**
     * Gets digg_count
     *
     * @return int
     */
    public function getDiggCount()
    {
        return $this->container['digg_count'];
    }

    /**
     * Sets digg_count
     *
     * @param int $digg_count digg_count
     *
     * @return $this
     */
    public function setDiggCount($digg_count)
    {
        $this->container['digg_count'] = $digg_count;

        return $this;
    }

    /**
     * Gets reply_comment_total
     *
     * @return int
     */
    public function getReplyCommentTotal()
    {
        return $this->container['reply_comment_total'];
    }

    /**
     * Sets reply_comment_total
     *
     * @param int $reply_comment_total 回复评论数
     *
     * @return $this
     */
    public function setReplyCommentTotal($reply_comment_total)
    {
        $this->container['reply_comment_total'] = $reply_comment_total;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
