<?php
/**
 * PoiSupplierApi
 * PHP version 5
 *
 * @category Class
 * @package  Douyin\Open
 * @author   抖音小开
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 */
/**
 * NOTE: 由抖音小开自动生成，请勿修改
 */

namespace Douyin\Open\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Douyin\Open\ApiException;
use Douyin\Open\Configuration;
use Douyin\Open\HeaderSelector;
use Douyin\Open\ObjectSerializer;

/**
 * PoiSupplierApi Class Doc Comment
 *
 * @category Class
 * @package  Douyin\Open
 * @author   抖音小开
 */
class PoiSupplierApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation poiQueryGet
     *
     * 获取抖音POI ID
     *
     * @param  string $access_token 调用/oauth/client_token/生成的token，此token不需要用户授权。 (required)
     * @param  string $amap_id amap_id (required)
     *
     * @throws \Douyin\Open\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Douyin\Open\Model\PoiQueryResponse
     */
    public function poiQueryGet($access_token, $amap_id)
    {
        list($response) = $this->poiQueryGetWithHttpInfo($access_token, $amap_id);
        return $response;
    }

    /**
     * Operation poiQueryGetWithHttpInfo
     *
     * 获取抖音POI ID
     *
     * @param  string $access_token 调用/oauth/client_token/生成的token，此token不需要用户授权。 (required)
     * @param  string $amap_id (required)
     *
     * @throws \Douyin\Open\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Douyin\Open\Model\PoiQueryResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function poiQueryGetWithHttpInfo($access_token, $amap_id)
    {
        $returnType = '\Douyin\Open\Model\PoiQueryResponse';
        $request = $this->poiQueryGetRequest($access_token, $amap_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Douyin\Open\Model\PoiQueryResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Create request for operation 'poiQueryGet'
     *
     * @param  string $access_token 调用/oauth/client_token/生成的token，此token不需要用户授权。 (required)
     * @param  string $amap_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function poiQueryGetRequest($access_token, $amap_id)
    {
        // verify the required parameter 'access_token' is set
        if ($access_token === null || (is_array($access_token) && count($access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_token when calling poiQueryGet'
            );
        }
        // verify the required parameter 'amap_id' is set
        if ($amap_id === null || (is_array($amap_id) && count($amap_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $amap_id when calling poiQueryGet'
            );
        }

        $resourcePath = '/poi/query/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($access_token !== null) {
            $queryParams['access_token'] = ObjectSerializer::toQueryValue($access_token);
        }
        // query params
        if ($amap_id !== null) {
            $queryParams['amap_id'] = ObjectSerializer::toQueryValue($amap_id);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation poiSupplierQueryGet
     *
     * 查询店铺
     *
     * @param  string $access_token 调用/oauth/client_token/生成的token，此token不需要用户授权。 (required)
     * @param  string $supplier_ext_id supplier_ext_id (required)
     *
     * @throws \Douyin\Open\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Douyin\Open\Model\PoiSupplierQueryResponse
     */
    public function poiSupplierQueryGet($access_token, $supplier_ext_id)
    {
        list($response) = $this->poiSupplierQueryGetWithHttpInfo($access_token, $supplier_ext_id);
        return $response;
    }

    /**
     * Operation poiSupplierQueryGetWithHttpInfo
     *
     * 查询店铺
     *
     * @param  string $access_token 调用/oauth/client_token/生成的token，此token不需要用户授权。 (required)
     * @param  string $supplier_ext_id (required)
     *
     * @throws \Douyin\Open\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Douyin\Open\Model\PoiSupplierQueryResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function poiSupplierQueryGetWithHttpInfo($access_token, $supplier_ext_id)
    {
        $returnType = '\Douyin\Open\Model\PoiSupplierQueryResponse';
        $request = $this->poiSupplierQueryGetRequest($access_token, $supplier_ext_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Douyin\Open\Model\PoiSupplierQueryResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Create request for operation 'poiSupplierQueryGet'
     *
     * @param  string $access_token 调用/oauth/client_token/生成的token，此token不需要用户授权。 (required)
     * @param  string $supplier_ext_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function poiSupplierQueryGetRequest($access_token, $supplier_ext_id)
    {
        // verify the required parameter 'access_token' is set
        if ($access_token === null || (is_array($access_token) && count($access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_token when calling poiSupplierQueryGet'
            );
        }
        // verify the required parameter 'supplier_ext_id' is set
        if ($supplier_ext_id === null || (is_array($supplier_ext_id) && count($supplier_ext_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $supplier_ext_id when calling poiSupplierQueryGet'
            );
        }

        $resourcePath = '/poi/supplier/query/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($access_token !== null) {
            $queryParams['access_token'] = ObjectSerializer::toQueryValue($access_token);
        }
        // query params
        if ($supplier_ext_id !== null) {
            $queryParams['supplier_ext_id'] = ObjectSerializer::toQueryValue($supplier_ext_id);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation poiSupplierSyncPost
     *
     * 商铺同步
     *
     * @param  \Douyin\Open\Model\PoiSupplierSyncBody $body body (required)
     * @param  string $access_token 调用/oauth/client_token/生成的token，此token不需要用户授权。 (required)
     *
     * @throws \Douyin\Open\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Douyin\Open\Model\PoiSupplierSyncResponse
     */
    public function poiSupplierSyncPost($body, $access_token)
    {
        list($response) = $this->poiSupplierSyncPostWithHttpInfo($body, $access_token);
        return $response;
    }

    /**
     * Operation poiSupplierSyncPostWithHttpInfo
     *
     * 商铺同步
     *
     * @param  \Douyin\Open\Model\PoiSupplierSyncBody $body (required)
     * @param  string $access_token 调用/oauth/client_token/生成的token，此token不需要用户授权。 (required)
     *
     * @throws \Douyin\Open\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Douyin\Open\Model\PoiSupplierSyncResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function poiSupplierSyncPostWithHttpInfo($body, $access_token)
    {
        $returnType = '\Douyin\Open\Model\PoiSupplierSyncResponse';
        $request = $this->poiSupplierSyncPostRequest($body, $access_token);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Douyin\Open\Model\PoiSupplierSyncResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Create request for operation 'poiSupplierSyncPost'
     *
     * @param  \Douyin\Open\Model\PoiSupplierSyncBody $body (required)
     * @param  string $access_token 调用/oauth/client_token/生成的token，此token不需要用户授权。 (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function poiSupplierSyncPostRequest($body, $access_token)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling poiSupplierSyncPost'
            );
        }
        // verify the required parameter 'access_token' is set
        if ($access_token === null || (is_array($access_token) && count($access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_token when calling poiSupplierSyncPost'
            );
        }

        $resourcePath = '/poi/supplier/sync/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($access_token !== null) {
            $queryParams['access_token'] = ObjectSerializer::toQueryValue($access_token);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
