<?php
/**
 * EnterpriseLeadsUserActionListResponseDataListTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Douyin\Open
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 企业号意向用户管理
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Douyin\Open;

/**
 * EnterpriseLeadsUserActionListResponseDataListTest Class Doc Comment
 *
 * @category    Class
 * @description EnterpriseLeadsUserActionListResponseDataList
 * @package     Douyin\Open
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseLeadsUserActionListResponseDataListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnterpriseLeadsUserActionListResponseDataList"
     */
    public function testEnterpriseLeadsUserActionListResponseDataList()
    {
    }

    /**
     * Test attribute "action_type"
     */
    public function testPropertyActionType()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "action_source"
     */
    public function testPropertyActionSource()
    {
    }

    /**
     * Test attribute "action_flag"
     */
    public function testPropertyActionFlag()
    {
    }

    /**
     * Test attribute "create_time"
     */
    public function testPropertyCreateTime()
    {
    }
}
