<?php
/**
 * FansDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Douyin\Open
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 获取用户的粉丝数据
 *
 * OpenAPI spec version: 1.0.0
 * 
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Douyin\Open;

/**
 * FansDataTest Class Doc Comment
 *
 * @category    Class
 * @description FansData
 * @package     Douyin\Open
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FansDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FansData"
     */
    public function testFansData()
    {
    }

    /**
     * Test attribute "all_fans_num"
     */
    public function testPropertyAllFansNum()
    {
    }

    /**
     * Test attribute "gender_distributions"
     */
    public function testPropertyGenderDistributions()
    {
    }

    /**
     * Test attribute "age_distributions"
     */
    public function testPropertyAgeDistributions()
    {
    }

    /**
     * Test attribute "geographical_distributions"
     */
    public function testPropertyGeographicalDistributions()
    {
    }

    /**
     * Test attribute "active_days_distributions"
     */
    public function testPropertyActiveDaysDistributions()
    {
    }

    /**
     * Test attribute "device_distributions"
     */
    public function testPropertyDeviceDistributions()
    {
    }

    /**
     * Test attribute "interest_distributions"
     */
    public function testPropertyInterestDistributions()
    {
    }

    /**
     * Test attribute "flow_contributions"
     */
    public function testPropertyFlowContributions()
    {
    }
}
