<?php
/**
 * HotsearchSentencesResponseDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Douyin\Open
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Douyin\Open;

/**
 * HotsearchSentencesResponseDataTest Class Doc Comment
 *
 * @category    Class
 * @description HotsearchSentencesResponseData
 * @package     Douyin\Open
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HotsearchSentencesResponseDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HotsearchSentencesResponseData"
     */
    public function testHotsearchSentencesResponseData()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "active_time"
     */
    public function testPropertyActiveTime()
    {
    }

    /**
     * Test attribute "list"
     */
    public function testPropertyList()
    {
    }
}
