<?php
/**
 * PoiSupplierSyncServicesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Douyin\Open
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Douyin\Open;

/**
 * PoiSupplierSyncServicesTest Class Doc Comment
 *
 * @category    Class
 * @description 服务项
 * @package     Douyin\Open
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PoiSupplierSyncServicesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PoiSupplierSyncServices"
     */
    public function testPoiSupplierSyncServices()
    {
    }

    /**
     * Test attribute "service_type"
     */
    public function testPropertyServiceType()
    {
    }

    /**
     * Test attribute "enable"
     */
    public function testPropertyEnable()
    {
    }

    /**
     * Test attribute "entry"
     */
    public function testPropertyEntry()
    {
    }
}
