<?php
/**
 * StarAuthorScoreResponseDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Douyin\Open
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Douyin\Open;

/**
 * StarAuthorScoreResponseDataTest Class Doc Comment
 *
 * @category    Class
 * @description StarAuthorScoreResponseData
 * @package     Douyin\Open
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StarAuthorScoreResponseDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StarAuthorScoreResponseData"
     */
    public function testStarAuthorScoreResponseData()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "update_timestamp"
     */
    public function testPropertyUpdateTimestamp()
    {
    }

    /**
     * Test attribute "nick_name"
     */
    public function testPropertyNickName()
    {
    }

    /**
     * Test attribute "follower"
     */
    public function testPropertyFollower()
    {
    }

    /**
     * Test attribute "spread_score"
     */
    public function testPropertySpreadScore()
    {
    }

    /**
     * Test attribute "cp_score"
     */
    public function testPropertyCpScore()
    {
    }

    /**
     * Test attribute "growth_score"
     */
    public function testPropertyGrowthScore()
    {
    }

    /**
     * Test attribute "cooperation_score"
     */
    public function testPropertyCooperationScore()
    {
    }

    /**
     * Test attribute "shop_score"
     */
    public function testPropertyShopScore()
    {
    }

    /**
     * Test attribute "star_score"
     */
    public function testPropertyStarScore()
    {
    }
}
