<?php
/**
 * SupplierAttributes3101Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Douyin\Open
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Douyin\Open;

/**
 * SupplierAttributes3101Test Class Doc Comment
 *
 * @category    Class
 * @description 景区须知
 * @package     Douyin\Open
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SupplierAttributes3101Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SupplierAttributes3101"
     */
    public function testSupplierAttributes3101()
    {
    }

    /**
     * Test attribute "open_time"
     */
    public function testPropertyOpenTime()
    {
    }

    /**
     * Test attribute "open_time_ext"
     */
    public function testPropertyOpenTimeExt()
    {
    }

    /**
     * Test attribute "preferential_policy"
     */
    public function testPropertyPreferentialPolicy()
    {
    }

    /**
     * Test attribute "preferential_policy_ext"
     */
    public function testPropertyPreferentialPolicyExt()
    {
    }

    /**
     * Test attribute "facility"
     */
    public function testPropertyFacility()
    {
    }

    /**
     * Test attribute "play_intro"
     */
    public function testPropertyPlayIntro()
    {
    }

    /**
     * Test attribute "traffic"
     */
    public function testPropertyTraffic()
    {
    }

    /**
     * Test attribute "pet"
     */
    public function testPropertyPet()
    {
    }

    /**
     * Test attribute "scenic_intro"
     */
    public function testPropertyScenicIntro()
    {
    }
}
