<?php
/**
 * SupplierAttributes1104Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Douyin\Open
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Douyin\Open;

/**
 * SupplierAttributes1104Test Class Doc Comment
 *
 * @category    Class
 * @description 酒店政策
 * @package     Douyin\Open
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SupplierAttributes1104Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SupplierAttributes1104"
     */
    public function testSupplierAttributes1104()
    {
    }

    /**
     * Test attribute "check_in_time"
     */
    public function testPropertyCheckInTime()
    {
    }

    /**
     * Test attribute "check_out_time"
     */
    public function testPropertyCheckOutTime()
    {
    }

    /**
     * Test attribute "breakfast"
     */
    public function testPropertyBreakfast()
    {
    }

    /**
     * Test attribute "child"
     */
    public function testPropertyChild()
    {
    }

    /**
     * Test attribute "pet"
     */
    public function testPropertyPet()
    {
    }
}
