<?php
/**
 * VideoDataResponseDataResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Douyin\Open
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 通过抖音视频id批量获取已分享视频数据信息
 *
 * OpenAPI spec version: 1.0.0
 * 
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Douyin\Open;

/**
 * VideoDataResponseDataResponseTest Class Doc Comment
 *
 * @category    Class
 * @description VideoDataResponseDataResponse
 * @package     Douyin\Open
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VideoDataResponseDataResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VideoDataResponseDataResponse"
     */
    public function testVideoDataResponseDataResponse()
    {
    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "create_time"
     */
    public function testPropertyCreateTime()
    {
    }

    /**
     * Test attribute "digg"
     */
    public function testPropertyDigg()
    {
    }

    /**
     * Test attribute "play"
     */
    public function testPropertyPlay()
    {
    }

    /**
     * Test attribute "forward"
     */
    public function testPropertyForward()
    {
    }

    /**
     * Test attribute "is_reviewed"
     */
    public function testPropertyIsReviewed()
    {
    }
}
