<?php
/**
 * VideoCommentListResponseDataListTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Douyin\Open
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Douyin\Open;

/**
 * VideoCommentListResponseDataListTest Class Doc Comment
 *
 * @category    Class
 * @description VideoCommentListResponseDataList
 * @package     Douyin\Open
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VideoCommentListResponseDataListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VideoCommentListResponseDataList"
     */
    public function testVideoCommentListResponseDataList()
    {
    }

    /**
     * Test attribute "comment_id"
     */
    public function testPropertyCommentId()
    {
    }

    /**
     * Test attribute "comment_user_id"
     */
    public function testPropertyCommentUserId()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "create_time"
     */
    public function testPropertyCreateTime()
    {
    }

    /**
     * Test attribute "top"
     */
    public function testPropertyTop()
    {
    }

    /**
     * Test attribute "digg_count"
     */
    public function testPropertyDiggCount()
    {
    }

    /**
     * Test attribute "reply_comment_total"
     */
    public function testPropertyReplyCommentTotal()
    {
    }
}
